# Wipe the tables clean
User.destroy_all
Transaction.destroy_all

# Create users
brian_user = User.new({ name: "Brian" })
brian_user.save
ben_user = User.new({ name: "Ben" })
ben_user.save
evan_user = User.new({ name: "Evan" })
evan_user.save
anthony_user = User.new({ name: "Anthony" })
anthony_user.save
krystina_user = User.new({ name: "Krystina" })
krystina_user.save

# The transactions
Transaction.create({ from_user: nil, to_user: ben_user, amount: 10000 })
Transaction.create({ from_user: ben_user, to_user: brian_user, amount: 1557 })
Transaction.create({ from_user: ben_user, to_user: evan_user, amount: 1509 })
Transaction.create({ from_user: brian_user, to_user: krystina_user, amount: 922 })
Transaction.create({ from_user: evan_user, to_user: anthony_user, amount: 685 })
Transaction.create({ from_user: krystina_user, to_user: evan_user, amount: 677 })
Transaction.create({ from_user: krystina_user, to_user: brian_user, amount: 840 })
Transaction.create({ from_user: krystina_user, to_user: anthony_user, amount: 1862 })
Transaction.create({ from_user: ben_user, to_user: evan_user, amount: 302 })
Transaction.create({ from_user: evan_user, to_user: brian_user, amount: 703 })
Transaction.create({ from_user: evan_user, to_user: anthony_user, amount: 233 })
Transaction.create({ from_user: brian_user, to_user: anthony_user, amount: 81 })
Transaction.create({ from_user: evan_user, to_user: anthony_user, amount: 621 })
Transaction.create({ from_user: krystina_user, to_user: evan_user, amount: 937 })
Transaction.create({ from_user: ben_user, to_user: anthony_user, amount: 547 })
Transaction.create({ from_user: brian_user, to_user: anthony_user, amount: 979 })
Transaction.create({ from_user: anthony_user, to_user: krystina_user, amount: 2057 })
Transaction.create({ from_user: ben_user, to_user: anthony_user, amount: 896 })
Transaction.create({ from_user: evan_user, to_user: anthony_user, amount: 246 })
Transaction.create({ from_user: ben_user, to_user: brian_user, amount: 155 })
Transaction.create({ from_user: krystina_user, to_user: anthony_user, amount: 58 })
Transaction.create({ from_user: brian_user, to_user: krystina_user, amount: 93 })
Transaction.create({ from_user: ben_user, to_user: evan_user, amount: 748 })
Transaction.create({ from_user: ben_user, to_user: krystina_user, amount: 399 })
Transaction.create({ from_user: anthony_user, to_user: ben_user, amount: 479 })
Transaction.create({ from_user: evan_user, to_user: ben_user, amount: 1804 })
Transaction.create({ from_user: brian_user, to_user: evan_user, amount: 477 })
Transaction.create({ from_user: brian_user, to_user: evan_user, amount: 370 })
Transaction.create({ from_user: anthony_user, to_user: ben_user, amount: 26 })
Transaction.create({ from_user: ben_user, to_user: brian_user, amount: 23 })
Transaction.create({ from_user: brian_user, to_user: ben_user, amount: 1111 })
Transaction.create({ from_user: brian_user, to_user: anthony_user, amount: 738 })
Transaction.create({ from_user: anthony_user, to_user: krystina_user, amount: 927 })
Transaction.create({ from_user: ben_user, to_user: evan_user, amount: 484 })
Transaction.create({ from_user: evan_user, to_user: ben_user, amount: 556 })
Transaction.create({ from_user: ben_user, to_user: anthony_user, amount: 720 })
Transaction.create({ from_user: krystina_user, to_user: anthony_user, amount: 235 })
Transaction.create({ from_user: ben_user, to_user: brian_user, amount: 2256 })
Transaction.create({ from_user: brian_user, to_user: ben_user, amount: 785 })
Transaction.create({ from_user: anthony_user, to_user: ben_user, amount: 828 })
Transaction.create({ from_user: evan_user, to_user: anthony_user, amount: 890 })
Transaction.create({ from_user: krystina_user, to_user: brian_user, amount: 554 })
Transaction.create({ from_user: brian_user, to_user: evan_user, amount: 188 })
Transaction.create({ from_user: krystina_user, to_user: brian_user, amount: 673 })
Transaction.create({ from_user: anthony_user, to_user: evan_user, amount: 806 })
Transaction.create({ from_user: ben_user, to_user: anthony_user, amount: 791 })
Transaction.create({ from_user: anthony_user, to_user: ben_user, amount: 69 })
Transaction.create({ from_user: krystina_user, to_user: brian_user, amount: 865 })
Transaction.create({ from_user: brian_user, to_user: krystina_user, amount: 840 })
Transaction.create({ from_user: evan_user, to_user: ben_user, amount: 2055 })
Transaction.create({ from_user: ben_user, to_user: brian_user, amount: 483 })
Transaction.create({ from_user: evan_user, to_user: ben_user, amount: 340 })
Transaction.create({ from_user: ben_user, to_user: anthony_user, amount: 652 })
Transaction.create({ from_user: ben_user, to_user: evan_user, amount: 185 })
Transaction.create({ from_user: brian_user, to_user: ben_user, amount: 982 })
Transaction.create({ from_user: brian_user, to_user: anthony_user, amount: 188 })
Transaction.create({ from_user: krystina_user, to_user: evan_user, amount: 32 })
Transaction.create({ from_user: anthony_user, to_user: ben_user, amount: 888 })
Transaction.create({ from_user: anthony_user, to_user: brian_user, amount: 110 })
Transaction.create({ from_user: ben_user, to_user: anthony_user, amount: 235 })
Transaction.create({ from_user: ben_user, to_user: brian_user, amount: 576 })
Transaction.create({ from_user: ben_user, to_user: anthony_user, amount: 228 })
Transaction.create({ from_user: brian_user, to_user: anthony_user, amount: 857 })
Transaction.create({ from_user: ben_user, to_user: krystina_user, amount: 741 })
Transaction.create({ from_user: ben_user, to_user: anthony_user, amount: 930 })
Transaction.create({ from_user: evan_user, to_user: ben_user, amount: 385 })
Transaction.create({ from_user: anthony_user, to_user: krystina_user, amount: 5032 })
Transaction.create({ from_user: anthony_user, to_user: ben_user, amount: 213 })
Transaction.create({ from_user: evan_user, to_user: anthony_user, amount: 104 })
Transaction.create({ from_user: evan_user, to_user: brian_user, amount: 505 })
Transaction.create({ from_user: krystina_user, to_user: evan_user, amount: 929 })
Transaction.create({ from_user: brian_user, to_user: evan_user, amount: 486 })
Transaction.create({ from_user: krystina_user, to_user: evan_user, amount: 956 })
Transaction.create({ from_user: ben_user, to_user: brian_user, amount: 422 })
Transaction.create({ from_user: brian_user, to_user: ben_user, amount: 819 })
Transaction.create({ from_user: ben_user, to_user: evan_user, amount: 809 })
Transaction.create({ from_user: brian_user, to_user: evan_user, amount: 768 })
Transaction.create({ from_user: anthony_user, to_user: ben_user, amount: 851 })
Transaction.create({ from_user: evan_user, to_user: krystina_user, amount: 874 })
Transaction.create({ from_user: evan_user, to_user: brian_user, amount: 849 })
Transaction.create({ from_user: evan_user, to_user: krystina_user, amount: 896 })
Transaction.create({ from_user: ben_user, to_user: anthony_user, amount: 917 })
Transaction.create({ from_user: evan_user, to_user: anthony_user, amount: 685 })
Transaction.create({ from_user: ben_user, to_user: krystina_user, amount: 339 })
Transaction.create({ from_user: brian_user, to_user: anthony_user, amount: 781 })
Transaction.create({ from_user: krystina_user, to_user: anthony_user, amount: 24 })
Transaction.create({ from_user: brian_user, to_user: krystina_user, amount: 806 })
Transaction.create({ from_user: brian_user, to_user: anthony_user, amount: 463 })
Transaction.create({ from_user: evan_user, to_user: krystina_user, amount: 397 })
Transaction.create({ from_user: brian_user, to_user: anthony_user, amount: 323 })
Transaction.create({ from_user: evan_user, to_user: brian_user, amount: 146 })
Transaction.create({ from_user: anthony_user, to_user: krystina_user, amount: 186 })
Transaction.create({ from_user: ben_user, to_user: evan_user, amount: 644 })
Transaction.create({ from_user: krystina_user, to_user: anthony_user, amount: 795 })
Transaction.create({ from_user: krystina_user, to_user: ben_user, amount: 13 })
Transaction.create({ from_user: krystina_user, to_user: brian_user, amount: 958 })
Transaction.create({ from_user: krystina_user, to_user: ben_user, amount: 585 })
Transaction.create({ from_user: ben_user, to_user: evan_user, amount: 2831 })
Transaction.create({ from_user: brian_user, to_user: ben_user, amount: 106 })
Transaction.create({ from_user: anthony_user, to_user: brian_user, amount: 2836 })

puts "There are now #{User.all.count} users and #{Transaction.all.count} transactions."